title: Joel<br/>Koerwer<br/>.github<br/>.io
url: http://joelkoerwer.github.io
description: Gibberish about math, optics, chess, etc.
author:
    name: Joel Koerwer
version: 0.1

permalink: /:year/:month/:day/:title/
paginate: 5
pygments: true
markdown: kramdown

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
